### ISSUE TITLE
FreeCat Broken, fix not found yet.

### ISSUE THREAD

**Issue by JaydenDev** [JaydenDev/freecat#3]
The problem is in js/dynamic.js
When I type in the search bar and click the "go" button, It does nothing, must be a JS error.

**Comment by webdev03** [comment]
VS Code is giving errors because fc:settings and fc:home aren't defined... how do those values work?

**Comment by webdev03** [comment]
Yeah I think you need to make `fc:settings` a string `"fc:settings"` also with the other one. Also change the constant in https://github.com/JaydenDev/freecat/blob/main/src/js/dynamic.js#L2 to `let wsite = document.getElementById("searchbox").value` and Lines 4 and 7 of that file without the `const` prefix.

**Comment by JaydenDev** [comment]
Your requested fixes have not worked

**Comment by JaydenDev** [comment]
Firefox mistakes "fc:settings" and "fc:home" to be protocol related. Which may be the issue

**Comment by JaydenDev** [comment]
That issue was resolved. However it now redirects to src/fc-home.html when it should go to src/home.html

**Comment by JaydenDev** [comment]
Whenever anything is in the search box, it redirects to src/fc-home.html instead of where its supposed to go

**Comment by webdev03** [comment]
> Firefox mistakes "fc:settings" and "fc:home" to be protocol related. Which may be the issue
I thought this is based on pywebview right?
Also you are intercepting it using dynamic.js before handing it to pywebview...


> Whenever anything is in the search box, it redirects to src/fc-home.html instead of where its supposed to go

I'm going to see it again

**Comment by JaydenDev** [comment]
I can test the UI in firefox since its regular HTML/CSS/JS. I just can't test the actual browser in Firefox.

**Comment by webdev03** [comment]
> I can test the UI in firefox since its regular HTML/CSS/JS. I just can't test the actual browser in Firefox.

I think that you still have a syntax error: I don't think fc:home is defined

**Comment by JaydenDev** [comment]
you dont have to fork to run locally
just download as a zip

**Comment by JaydenDev** [comment]
anything in quotes doesn't have to be defined, since its a string.
